name: test
on:
- push
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
        - '2.4'
        - '2.7'
        runs-on:
        - ubuntu-latest

    runs-on: ${{ matrix.runs-on }}

    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - run: bundle exec rake test
